spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/paascloud_uac?characterEncoding=utf8&useSSL=false
paascloud:
  security:
    social:
      filterProcessesUrl: /uac/auth/callback
      qq:
        app-id: 1
        app-secret: 1
        providerId: qq
      weixin:
        app-id: 1
        app-secret: 1
        providerId: weixin
  aliyun:
    rocketMq:
      instanceName: paascloud-provider-uac
      consumerGroup: CID_UAC
      producerGroup: PID_UAC
  auth:
    rest-pwd-url: http://dev-login.test.net/resetPwd?resetPwdKey=
    active-user-url: http://dev-api.test.net:7979/uac/auth/activeUser/
    refresh-token-url: http://dev-api.test.net:7979/uac/oauth/token